package tool

import (
	"errors"
	"fmt"
	"reflect"
	"regexp"
	"sort"
	"strings"

	"github.com/xen0bit/smolbox/internal/protocol"
)

// A TemplateTool is a narrow, task-shaped tool that compiles to an ordinary
// exec request: the model fills in typed parameters and the template turns them
// into a shell command.
//
// This is the extension point, and it is deliberately the *only* one. Every
// tool the model can see — built-in or user-defined — ends up as a
// protocol.Request with Op fixed to exec, so there remains exactly one way into
// the guest no matter how many tools exist.
//
// The definition format lives here, in Go, so its schema is generated by `make
// generate` alongside everything else. That keeps "one definition, two
// runtimes" true of the extension mechanism itself, not just of the wire.
type TemplateTool struct {
	Name        string          `json:"name"`
	Description string          `json:"description"`
	Params      []TemplateParam `json:"params"`
	// Template is a shell command with {param} placeholders. Interpolations are
	// shell-quoted; {param:raw} opts out (see Compile).
	Template string `json:"template"`
	// TimeoutMS and MaxOutput default the request when the caller sets neither.
	TimeoutMS int `json:"timeout_ms,omitempty"`
	MaxOutput int `json:"max_output,omitempty"`
}

// TemplateParam is one typed input to a TemplateTool.
type TemplateParam struct {
	Name        string `json:"name"`
	Type        string `json:"type"` // "string" | "integer" | "number" | "boolean"
	Description string `json:"description"`
	Required    bool   `json:"required,omitempty"`
	Default     string `json:"default,omitempty"`
}

// Errors returned when a definition or a call cannot be used.
var (
	ErrBadTemplate = errors.New("tool: invalid template tool")
	ErrMissingArg  = errors.New("tool: missing required argument")
)

// ReservedNames are tool names a template may not take: shadowing the exec tool
// would let a user-defined macro impersonate the surface everything else is
// specified against.
var ReservedNames = map[string]bool{Name: true}

var (
	nameRe        = regexp.MustCompile(`^[a-z][a-z0-9_]{0,63}$`)
	placeholderRe = regexp.MustCompile(`\{([a-zA-Z_][a-zA-Z0-9_]*)(:raw)?\}`)
	paramTypes    = map[string]bool{"string": true, "integer": true, "number": true, "boolean": true}
)

// Validate reports whether a template tool is well formed. It is deliberately
// strict: a malformed tool that reaches the model wastes a turn and confuses it.
func (t TemplateTool) Validate() error {
	if !nameRe.MatchString(t.Name) {
		return fmt.Errorf("%w: name %q must match %s", ErrBadTemplate, t.Name, nameRe)
	}
	if ReservedNames[t.Name] {
		return fmt.Errorf("%w: name %q is reserved", ErrBadTemplate, t.Name)
	}
	if strings.TrimSpace(t.Description) == "" {
		return fmt.Errorf("%w: %s has no description", ErrBadTemplate, t.Name)
	}
	if strings.TrimSpace(t.Template) == "" {
		return fmt.Errorf("%w: %s has an empty template", ErrBadTemplate, t.Name)
	}
	if t.TimeoutMS < 0 || t.MaxOutput < 0 {
		return fmt.Errorf("%w: %s has a negative timeout_ms or max_output", ErrBadTemplate, t.Name)
	}

	declared := make(map[string]bool, len(t.Params))
	for _, p := range t.Params {
		if !nameRe.MatchString(p.Name) {
			return fmt.Errorf("%w: %s: parameter %q must match %s", ErrBadTemplate, t.Name, p.Name, nameRe)
		}
		if declared[p.Name] {
			return fmt.Errorf("%w: %s: duplicate parameter %q", ErrBadTemplate, t.Name, p.Name)
		}
		if !paramTypes[p.Type] {
			return fmt.Errorf("%w: %s: parameter %q has unknown type %q", ErrBadTemplate, t.Name, p.Name, p.Type)
		}
		if strings.TrimSpace(p.Description) == "" {
			return fmt.Errorf("%w: %s: parameter %q has no description", ErrBadTemplate, t.Name, p.Name)
		}
		declared[p.Name] = true
	}

	// Every placeholder must be declared. The reverse (a declared parameter the
	// template never uses) is allowed: it is harmless, and forbidding it would
	// break the obvious way to build a tool up incrementally.
	for _, m := range placeholderRe.FindAllStringSubmatch(t.Template, -1) {
		if !declared[m[1]] {
			return fmt.Errorf("%w: %s: template uses undeclared parameter {%s}", ErrBadTemplate, t.Name, m[1])
		}
	}
	return nil
}

// Compile turns a model's arguments into an exec request.
//
// Interpolations are single-quoted for the shell by default, so a value
// containing a space, a quote, or a semicolon lands as one argument rather than
// as syntax. {param:raw} opts out for the cases that genuinely need it (a glob,
// a flag list).
//
// This quoting is a correctness measure, not a security boundary: while
// run_terminal_command is exposed the model can already run arbitrary shell, so
// interpolation grants it nothing new. It becomes load-bearing the moment a
// session exposes only template tools — which is exactly why it is the default
// now rather than a later retrofit.
func (t TemplateTool) Compile(args map[string]any) (protocol.Request, error) {
	if err := t.Validate(); err != nil {
		return protocol.Request{}, err
	}

	byName := make(map[string]TemplateParam, len(t.Params))
	for _, p := range t.Params {
		byName[p.Name] = p
	}

	// Unknown arguments are rejected rather than ignored, matching DecodeArgs:
	// a hallucinated argument should come back as a correctable error, not be
	// silently dropped.
	known := make([]string, 0, len(t.Params))
	for _, p := range t.Params {
		known = append(known, p.Name)
	}
	sort.Strings(known)
	for k := range args {
		if _, ok := byName[k]; !ok {
			return protocol.Request{}, fmt.Errorf("%w: %s: unknown argument %q (known: %s)",
				ErrBadTemplate, t.Name, k, strings.Join(known, ", "))
		}
	}

	values := make(map[string]string, len(t.Params))
	for _, p := range t.Params {
		raw, ok := args[p.Name]
		if !ok || raw == nil {
			if p.Required {
				return protocol.Request{}, fmt.Errorf("%w: %s: %s", ErrMissingArg, t.Name, p.Name)
			}
			values[p.Name] = p.Default
			continue
		}
		s, err := scalarString(raw, p)
		if err != nil {
			return protocol.Request{}, fmt.Errorf("%w: %s: %v", ErrBadTemplate, t.Name, err)
		}
		values[p.Name] = s
	}

	cmd := placeholderRe.ReplaceAllStringFunc(t.Template, func(m string) string {
		sub := placeholderRe.FindStringSubmatch(m)
		name, raw := sub[1], sub[2] == ":raw"
		v := values[name]
		if raw {
			return v
		}
		return shellQuote(v)
	})

	return protocol.Request{
		// Fixed, never taken from arguments: a template tool is an exec surface
		// and nothing else, exactly like run_terminal_command.
		Op:        protocol.OpExec,
		Cmd:       cmd,
		TimeoutMS: t.TimeoutMS,
		MaxOutput: t.MaxOutput,
	}, nil
}

func scalarString(v any, p TemplateParam) (string, error) {
	switch p.Type {
	case "string":
		s, ok := v.(string)
		if !ok {
			return "", fmt.Errorf("%s must be a string", p.Name)
		}
		return s, nil
	case "boolean":
		b, ok := v.(bool)
		if !ok {
			return "", fmt.Errorf("%s must be a boolean", p.Name)
		}
		if b {
			return "true", nil
		}
		return "false", nil
	case "integer", "number":
		switch n := v.(type) {
		case float64:
			if p.Type == "integer" && n != float64(int64(n)) {
				return "", fmt.Errorf("%s must be an integer", p.Name)
			}
			return strings.TrimSuffix(fmt.Sprintf("%v", n), ".0"), nil
		case int:
			return fmt.Sprintf("%d", n), nil
		default:
			return "", fmt.Errorf("%s must be a number", p.Name)
		}
	}
	return "", fmt.Errorf("%s has unknown type %q", p.Name, p.Type)
}

// shellQuote wraps a value in single quotes, which sh treats as fully literal.
// The one character that cannot appear inside them is a single quote, so it is
// closed, escaped, and reopened — the standard POSIX dance.
func shellQuote(s string) string {
	return "'" + strings.ReplaceAll(s, "'", `'\''`) + "'"
}

// Definition renders the template tool for function calling, deriving the input
// schema from the declared parameters.
func (t TemplateTool) Definition() Definition {
	props := make([]Property, 0, len(t.Params))
	required := make([]string, 0, len(t.Params))
	for _, p := range t.Params {
		props = append(props, Property{
			Name:   p.Name,
			Schema: &Schema{Type: TypeSet{p.Type}, Description: p.Description},
		})
		if p.Required {
			required = append(required, p.Name)
		}
	}
	return Definition{
		Name:        t.Name,
		Description: t.Description,
		Input: &Schema{
			Dialect:    SchemaDialect,
			Title:      t.Name + " arguments",
			Type:       TypeSet{"object"},
			Properties: props,
			Required:   required,
		},
	}
}

// BuiltinTemplates are the narrow tools shipped with smolbox, off by default.
//
// They amend PLAN §4.5's "commands, not more tools", which was decided before
// there was a model to test it against. Whether they actually help a small
// model is an open question (PLAN §10.7): each definition costs roughly 2 KB of
// system prompt on every turn, so they are opt-in rather than automatic.
var BuiltinTemplates = []TemplateTool{
	{
		Name:        "list_dir",
		Description: "List the entries of a directory in the sandbox, one per line, with type and size.",
		Params: []TemplateParam{
			{Name: "path", Type: "string", Description: "Directory to list. Defaults to the mounted folder.", Default: "/mnt/host"},
		},
		Template: "ls -la {path}",
	},
	{
		Name:        "read_file",
		Description: "Read a file from the sandbox. Use this when you know the exact path; prefer search_files to find one.",
		Params: []TemplateParam{
			{Name: "path", Type: "string", Description: "Path of the file to read.", Required: true},
			{Name: "max_lines", Type: "integer", Description: "Stop after this many lines.", Default: "200"},
		},
		Template: "head -n {max_lines:raw} -- {path}",
	},
	{
		Name:        "search_files",
		Description: "Search the mounted folder for a text pattern, returning matching lines with their file and line number.",
		Params: []TemplateParam{
			{Name: "pattern", Type: "string", Description: "Text or basic regular expression to search for.", Required: true},
			{Name: "path", Type: "string", Description: "Directory to search. Defaults to the mounted folder.", Default: "/mnt/host"},
		},
		Template: "grep -rn -- {pattern} {path}",
	},
}

// TemplateToolSchema is the JSON Schema of the TemplateTool definition format
// itself, derived from the Go structs by the same reflection that produces the
// wire schemas. The browser validates user-defined tools against this, so the
// format cannot drift between the two runtimes.
var TemplateToolSchema = buildTemplateToolSchema()

// Registering the parameter schema inside the builder makes Go's initialisation
// order do the right thing: this function references templateParamSchema, so
// that variable is initialised first.
func buildTemplateToolSchema() *Schema {
	nestedSchemas[reflect.TypeFor[TemplateParam]()] = templateParamSchema
	return mustSchema(reflect.TypeFor[TemplateTool](), "smolbox template tool definition", map[string]string{
		"name":        "Function-calling name. Lowercase letters, digits and underscores; must not be `run_terminal_command`.",
		"description": "What the tool does, in the words the model will read. This is prompt text on every turn, so keep it to a sentence or two.",
		"params":      "The typed inputs the model fills in.",
		"template":    "A shell command with {param} placeholders. Interpolations are shell-quoted; use {param:raw} to insert a value literally.",
		"timeout_ms":  "Kill the command after this many milliseconds. 0 means no timeout.",
		"max_output":  "Cap stdout and stderr at this many bytes each. 0 uses the session default.",
	})
}

var templateParamSchema = mustSchema(reflect.TypeFor[TemplateParam](), "smolbox template tool parameter", map[string]string{
	"name":        "Parameter name, as the model will pass it.",
	"type":        "One of string, integer, number, boolean.",
	"description": "What the model should put here.",
	"required":    "Whether the model must supply a value.",
	"default":     "Value used when the model omits an optional parameter.",
})
